/*
 * Created on 24 Mar 2016 ( Time 12:52:04 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResAddonService;
import com.itigeeks.restaurant.common.entity.schema.ResAddon;
import com.itigeeks.restaurant.dataaccess.dao.ResAddonDAO;
/**
 * Implementation of ResAddonService
 */
@Service
public class ResAddonServiceImpl implements ResAddonService {


	@Autowired
	private ResAddonDAO resAddonDAO;

	public void delete(ResAddon resAddon)
	{
		 resAddonDAO.delete(resAddon);
	}
	
	public ResAddon saveOrUpdate(ResAddon resAddon)
	{
		return resAddonDAO.saveOrUpdate( resAddon);
	}

	public ResAddon load(Long id )
	{
		return resAddonDAO.load( id );
	}

	
	public List<ResAddon> loadAll()
	{
		return resAddonDAO.loadAll();
	}


	public List<ResAddon> loadByNamedQuery(String queryName)
	{
		return resAddonDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResAddon> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resAddonDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResAddon> search( Map<String, Object> criteria )
	{
		return resAddonDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resAddonDAO.countAll();
	}

	public List<ResAddon> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resAddonDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResAddon> loadAll(Integer startPage , Integer pageSize )
	{

		return resAddonDAO.loadAll( startPage ,  pageSize );
	}

}
