/*
 * Created on 20 Mar 2016 ( Time 14:19:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResCallLogService;
import com.itigeeks.restaurant.common.entity.schema.ResCallLog;
import com.itigeeks.restaurant.dataaccess.dao.ResCallLogDAO;
/**
 * Implementation of ResCallLogService
 */
@Service
public class ResCallLogServiceImpl implements ResCallLogService {


	@Autowired
	private ResCallLogDAO resCallLogDAO;

	public void delete(ResCallLog resCallLog)
	{
		 resCallLogDAO.delete(resCallLog);
	}
	
	public ResCallLog saveOrUpdate(ResCallLog resCallLog)
	{
		return resCallLogDAO.saveOrUpdate( resCallLog);
	}

	public ResCallLog load(Long id )
	{
		return resCallLogDAO.load( id );
	}

	
	public List<ResCallLog> loadAll()
	{
		return resCallLogDAO.loadAll();
	}


	public List<ResCallLog> loadByNamedQuery(String queryName)
	{
		return resCallLogDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResCallLog> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resCallLogDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResCallLog> search( Map<String, Object> criteria )
	{
		return resCallLogDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resCallLogDAO.countAll();
	}

}
