/*
 * Created on 20 Mar 2016 ( Time 14:19:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResCityService;
import com.itigeeks.restaurant.common.entity.schema.ResCity;
import com.itigeeks.restaurant.dataaccess.dao.ResCityDAO;
/**
 * Implementation of ResCityService
 */
@Service
public class ResCityServiceImpl implements ResCityService {


	@Autowired
	private ResCityDAO resCityDAO;

	public void delete(ResCity resCity)
	{
		 resCityDAO.delete(resCity);
	}
	
	public ResCity saveOrUpdate(ResCity resCity)
	{
		return resCityDAO.saveOrUpdate( resCity);
	}

	public ResCity load(Long id )
	{
		return resCityDAO.load( id );
	}

	
	public List<ResCity> loadAll()
	{
		return resCityDAO.loadAll();
	}


	public List<ResCity> loadByNamedQuery(String queryName)
	{
		return resCityDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResCity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resCityDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResCity> search( Map<String, Object> criteria )
	{
		return resCityDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resCityDAO.countAll();
	}

}
