/*
 * Created on 20 Mar 2016 ( Time 14:19:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResCountryService;
import com.itigeeks.restaurant.common.entity.schema.ResCountry;
import com.itigeeks.restaurant.dataaccess.dao.ResCountryDAO;
/**
 * Implementation of ResCountryService
 */
@Service
public class ResCountryServiceImpl implements ResCountryService {


	@Autowired
	private ResCountryDAO resCountryDAO;

	public void delete(ResCountry resCountry)
	{
		 resCountryDAO.delete(resCountry);
	}
	
	public ResCountry saveOrUpdate(ResCountry resCountry)
	{
		return resCountryDAO.saveOrUpdate( resCountry);
	}

	public ResCountry load(Long id )
	{
		return resCountryDAO.load( id );
	}

	
	public List<ResCountry> loadAll()
	{
		return resCountryDAO.loadAll();
	}


	public List<ResCountry> loadByNamedQuery(String queryName)
	{
		return resCountryDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResCountry> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resCountryDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResCountry> search( Map<String, Object> criteria )
	{
		return resCountryDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resCountryDAO.countAll();
	}

}
