/*
 * Created on 20 Mar 2016 ( Time 14:19:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResCardTypeService;
import com.itigeeks.restaurant.common.entity.schema.ResCardType;
import com.itigeeks.restaurant.dataaccess.dao.ResCardTypeDAO;
/**
 * Implementation of ResCardTypeService
 */
@Service
public class ResCardTypeServiceImpl implements ResCardTypeService {


	@Autowired
	private ResCardTypeDAO resCardTypeDAO;

	public void delete(ResCardType resCardType)
	{
		 resCardTypeDAO.delete(resCardType);
	}
	
	public ResCardType saveOrUpdate(ResCardType resCardType)
	{
		return resCardTypeDAO.saveOrUpdate( resCardType);
	}

	public ResCardType load(Long id )
	{
		return resCardTypeDAO.load( id );
	}

	
	public List<ResCardType> loadAll()
	{
		return resCardTypeDAO.loadAll();
	}


	public List<ResCardType> loadByNamedQuery(String queryName)
	{
		return resCardTypeDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResCardType> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resCardTypeDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResCardType> search( Map<String, Object> criteria )
	{
		return resCardTypeDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resCardTypeDAO.countAll();
	}

}
