/*
 * Created on 20 Mar 2016 ( Time 14:19:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResCustomerAddressService;
import com.itigeeks.restaurant.common.entity.schema.ResCustomerAddress;
import com.itigeeks.restaurant.dataaccess.dao.ResCustomerAddressDAO;
/**
 * Implementation of ResCustomerAddressService
 */
@Service
public class ResCustomerAddressServiceImpl implements ResCustomerAddressService {


	@Autowired
	private ResCustomerAddressDAO resCustomerAddressDAO;

	public void delete(ResCustomerAddress resCustomerAddress)
	{
		 resCustomerAddressDAO.delete(resCustomerAddress);
	}
	
	public ResCustomerAddress saveOrUpdate(ResCustomerAddress resCustomerAddress)
	{
		return resCustomerAddressDAO.saveOrUpdate( resCustomerAddress);
	}

	public ResCustomerAddress load(Long id )
	{
		return resCustomerAddressDAO.load( id );
	}

	
	public List<ResCustomerAddress> loadAll()
	{
		return resCustomerAddressDAO.loadAll();
	}


	public List<ResCustomerAddress> loadByNamedQuery(String queryName)
	{
		return resCustomerAddressDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResCustomerAddress> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resCustomerAddressDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResCustomerAddress> search( Map<String, Object> criteria )
	{
		return resCustomerAddressDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resCustomerAddressDAO.countAll();
	}

}
