/*
 * Created on 20 Mar 2016 ( Time 14:19:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResCategoryService;
import com.itigeeks.restaurant.common.entity.schema.ResCategory;
import com.itigeeks.restaurant.dataaccess.dao.ResCategoryDAO;
/**
 * Implementation of ResCategoryService
 */
@Service
public class ResCategoryServiceImpl implements ResCategoryService {


	@Autowired
	private ResCategoryDAO resCategoryDAO;

	public void delete(ResCategory resCategory)
	{
		 resCategoryDAO.delete(resCategory);
	}
	
	public ResCategory saveOrUpdate(ResCategory resCategory)
	{
		return resCategoryDAO.saveOrUpdate( resCategory);
	}

	public ResCategory load(Long id )
	{
		return resCategoryDAO.load( id );
	}

	
	public List<ResCategory> loadAll()
	{
		return resCategoryDAO.loadAll();
	}


	public List<ResCategory> loadByNamedQuery(String queryName)
	{
		return resCategoryDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResCategory> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resCategoryDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResCategory> search( Map<String, Object> criteria )
	{
		return resCategoryDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resCategoryDAO.countAll();
	}

}
