/*
 * Created on 24 Mar 2016 ( Time 12:52:05 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResCustomerMessageService;
import com.itigeeks.restaurant.common.entity.schema.ResCustomerMessage;
import com.itigeeks.restaurant.dataaccess.dao.ResCustomerMessageDAO;
/**
 * Implementation of ResCustomerMessageService
 */
@Service
public class ResCustomerMessageServiceImpl implements ResCustomerMessageService {


	@Autowired
	private ResCustomerMessageDAO resCustomerMessageDAO;

	public void delete(ResCustomerMessage resCustomerMessage)
	{
		 resCustomerMessageDAO.delete(resCustomerMessage);
	}
	
	public ResCustomerMessage saveOrUpdate(ResCustomerMessage resCustomerMessage)
	{
		return resCustomerMessageDAO.saveOrUpdate( resCustomerMessage);
	}

	public ResCustomerMessage load(Long id )
	{
		return resCustomerMessageDAO.load( id );
	}

	
	public List<ResCustomerMessage> loadAll()
	{
		return resCustomerMessageDAO.loadAll();
	}


	public List<ResCustomerMessage> loadByNamedQuery(String queryName)
	{
		return resCustomerMessageDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResCustomerMessage> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resCustomerMessageDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResCustomerMessage> search( Map<String, Object> criteria )
	{
		return resCustomerMessageDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resCustomerMessageDAO.countAll();
	}

	public List<ResCustomerMessage> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resCustomerMessageDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResCustomerMessage> loadAll(Integer startPage , Integer pageSize )
	{

		return resCustomerMessageDAO.loadAll( startPage ,  pageSize );
	}

}
