/*
 * Created on 24 Mar 2016 ( Time 12:52:05 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResConvertedToTakeAwayService;
import com.itigeeks.restaurant.common.entity.schema.ResConvertedToTakeAway;
import com.itigeeks.restaurant.dataaccess.dao.ResConvertedToTakeAwayDAO;
/**
 * Implementation of ResConvertedToTakeAwayService
 */
@Service
public class ResConvertedToTakeAwayServiceImpl implements ResConvertedToTakeAwayService {


	@Autowired
	private ResConvertedToTakeAwayDAO resConvertedToTakeAwayDAO;

	public void delete(ResConvertedToTakeAway resConvertedToTakeAway)
	{
		 resConvertedToTakeAwayDAO.delete(resConvertedToTakeAway);
	}
	
	public ResConvertedToTakeAway saveOrUpdate(ResConvertedToTakeAway resConvertedToTakeAway)
	{
		return resConvertedToTakeAwayDAO.saveOrUpdate( resConvertedToTakeAway);
	}

	public ResConvertedToTakeAway load(Long id )
	{
		return resConvertedToTakeAwayDAO.load( id );
	}

	
	public List<ResConvertedToTakeAway> loadAll()
	{
		return resConvertedToTakeAwayDAO.loadAll();
	}


	public List<ResConvertedToTakeAway> loadByNamedQuery(String queryName)
	{
		return resConvertedToTakeAwayDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResConvertedToTakeAway> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resConvertedToTakeAwayDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResConvertedToTakeAway> search( Map<String, Object> criteria )
	{
		return resConvertedToTakeAwayDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resConvertedToTakeAwayDAO.countAll();
	}

	public List<ResConvertedToTakeAway> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resConvertedToTakeAwayDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResConvertedToTakeAway> loadAll(Integer startPage , Integer pageSize )
	{

		return resConvertedToTakeAwayDAO.loadAll( startPage ,  pageSize );
	}

}
