/*
 * Created on 20 Mar 2016 ( Time 14:19:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResCombineReportPermissionService;
import com.itigeeks.restaurant.common.entity.schema.ResCombineReportPermission;
import com.itigeeks.restaurant.dataaccess.dao.ResCombineReportPermissionDAO;
/**
 * Implementation of ResCombineReportPermissionService
 */
@Service
public class ResCombineReportPermissionServiceImpl implements ResCombineReportPermissionService {


	@Autowired
	private ResCombineReportPermissionDAO resCombineReportPermissionDAO;

	public void delete(ResCombineReportPermission resCombineReportPermission)
	{
		 resCombineReportPermissionDAO.delete(resCombineReportPermission);
	}
	
	public ResCombineReportPermission saveOrUpdate(ResCombineReportPermission resCombineReportPermission)
	{
		return resCombineReportPermissionDAO.saveOrUpdate( resCombineReportPermission);
	}

	public ResCombineReportPermission load(Long id )
	{
		return resCombineReportPermissionDAO.load( id );
	}

	
	public List<ResCombineReportPermission> loadAll()
	{
		return resCombineReportPermissionDAO.loadAll();
	}


	public List<ResCombineReportPermission> loadByNamedQuery(String queryName)
	{
		return resCombineReportPermissionDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResCombineReportPermission> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resCombineReportPermissionDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResCombineReportPermission> search( Map<String, Object> criteria )
	{
		return resCombineReportPermissionDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resCombineReportPermissionDAO.countAll();
	}

}
