/*
 * Created on 24 Mar 2016 ( Time 12:52:05 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResDbbackupSettingsService;
import com.itigeeks.restaurant.common.entity.schema.ResDbbackupSettings;
import com.itigeeks.restaurant.dataaccess.dao.ResDbbackupSettingsDAO;
/**
 * Implementation of ResDbbackupSettingsService
 */
@Service
public class ResDbbackupSettingsServiceImpl implements ResDbbackupSettingsService {


	@Autowired
	private ResDbbackupSettingsDAO resDbbackupSettingsDAO;

	public void delete(ResDbbackupSettings resDbbackupSettings)
	{
		 resDbbackupSettingsDAO.delete(resDbbackupSettings);
	}
	
	public ResDbbackupSettings saveOrUpdate(ResDbbackupSettings resDbbackupSettings)
	{
		return resDbbackupSettingsDAO.saveOrUpdate( resDbbackupSettings);
	}

	public ResDbbackupSettings load(Long id )
	{
		return resDbbackupSettingsDAO.load( id );
	}

	
	public List<ResDbbackupSettings> loadAll()
	{
		return resDbbackupSettingsDAO.loadAll();
	}


	public List<ResDbbackupSettings> loadByNamedQuery(String queryName)
	{
		return resDbbackupSettingsDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResDbbackupSettings> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resDbbackupSettingsDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResDbbackupSettings> search( Map<String, Object> criteria )
	{
		return resDbbackupSettingsDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resDbbackupSettingsDAO.countAll();
	}

	public List<ResDbbackupSettings> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resDbbackupSettingsDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResDbbackupSettings> loadAll(Integer startPage , Integer pageSize )
	{

		return resDbbackupSettingsDAO.loadAll( startPage ,  pageSize );
	}

}
