/*
 * Created on 24 Mar 2016 ( Time 12:52:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResDeliveryChargesService;
import com.itigeeks.restaurant.common.entity.schema.ResDeliveryCharges;
import com.itigeeks.restaurant.dataaccess.dao.ResDeliveryChargesDAO;
/**
 * Implementation of ResDeliveryChargesService
 */
@Service
public class ResDeliveryChargesServiceImpl implements ResDeliveryChargesService {


	@Autowired
	private ResDeliveryChargesDAO resDeliveryChargesDAO;

	public void delete(ResDeliveryCharges resDeliveryCharges)
	{
		 resDeliveryChargesDAO.delete(resDeliveryCharges);
	}
	
	public ResDeliveryCharges saveOrUpdate(ResDeliveryCharges resDeliveryCharges)
	{
		return resDeliveryChargesDAO.saveOrUpdate( resDeliveryCharges);
	}

	public ResDeliveryCharges load(Long id )
	{
		return resDeliveryChargesDAO.load( id );
	}

	
	public List<ResDeliveryCharges> loadAll()
	{
		return resDeliveryChargesDAO.loadAll();
	}


	public List<ResDeliveryCharges> loadByNamedQuery(String queryName)
	{
		return resDeliveryChargesDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResDeliveryCharges> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resDeliveryChargesDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResDeliveryCharges> search( Map<String, Object> criteria )
	{
		return resDeliveryChargesDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resDeliveryChargesDAO.countAll();
	}

	public List<ResDeliveryCharges> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resDeliveryChargesDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResDeliveryCharges> loadAll(Integer startPage , Integer pageSize )
	{

		return resDeliveryChargesDAO.loadAll( startPage ,  pageSize );
	}

}
