/*
 * Created on 24 Mar 2016 ( Time 12:52:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResDepositTypeService;
import com.itigeeks.restaurant.common.entity.schema.ResDepositType;
import com.itigeeks.restaurant.dataaccess.dao.ResDepositTypeDAO;
/**
 * Implementation of ResDepositTypeService
 */
@Service
public class ResDepositTypeServiceImpl implements ResDepositTypeService {


	@Autowired
	private ResDepositTypeDAO resDepositTypeDAO;

	public void delete(ResDepositType resDepositType)
	{
		 resDepositTypeDAO.delete(resDepositType);
	}
	
	public ResDepositType saveOrUpdate(ResDepositType resDepositType)
	{
		return resDepositTypeDAO.saveOrUpdate( resDepositType);
	}

	public ResDepositType load(Long id )
	{
		return resDepositTypeDAO.load( id );
	}

	
	public List<ResDepositType> loadAll()
	{
		return resDepositTypeDAO.loadAll();
	}


	public List<ResDepositType> loadByNamedQuery(String queryName)
	{
		return resDepositTypeDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResDepositType> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resDepositTypeDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResDepositType> search( Map<String, Object> criteria )
	{
		return resDepositTypeDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resDepositTypeDAO.countAll();
	}

	public List<ResDepositType> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resDepositTypeDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResDepositType> loadAll(Integer startPage , Integer pageSize )
	{

		return resDepositTypeDAO.loadAll( startPage ,  pageSize );
	}

}
