/*
 * Created on 20 Mar 2016 ( Time 14:19:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResDeliverChargesService;
import com.itigeeks.restaurant.common.entity.schema.ResDeliverCharges;
import com.itigeeks.restaurant.dataaccess.dao.ResDeliverChargesDAO;
/**
 * Implementation of ResDeliverChargesService
 */
@Service
public class ResDeliverChargesServiceImpl implements ResDeliverChargesService {


	@Autowired
	private ResDeliverChargesDAO resDeliverChargesDAO;

	public void delete(ResDeliverCharges resDeliverCharges)
	{
		 resDeliverChargesDAO.delete(resDeliverCharges);
	}
	
	public ResDeliverCharges saveOrUpdate(ResDeliverCharges resDeliverCharges)
	{
		return resDeliverChargesDAO.saveOrUpdate( resDeliverCharges);
	}

	public ResDeliverCharges load(Long id )
	{
		return resDeliverChargesDAO.load( id );
	}

	
	public List<ResDeliverCharges> loadAll()
	{
		return resDeliverChargesDAO.loadAll();
	}


	public List<ResDeliverCharges> loadByNamedQuery(String queryName)
	{
		return resDeliverChargesDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResDeliverCharges> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resDeliverChargesDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResDeliverCharges> search( Map<String, Object> criteria )
	{
		return resDeliverChargesDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resDeliverChargesDAO.countAll();
	}

}
