/*
 * Created on 24 Mar 2016 ( Time 12:52:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResDiscountProductService;
import com.itigeeks.restaurant.common.entity.schema.ResDiscountProduct;
import com.itigeeks.restaurant.dataaccess.dao.ResDiscountProductDAO;
/**
 * Implementation of ResDiscountProductService
 */
@Service
public class ResDiscountProductServiceImpl implements ResDiscountProductService {


	@Autowired
	private ResDiscountProductDAO resDiscountProductDAO;

	public void delete(ResDiscountProduct resDiscountProduct)
	{
		 resDiscountProductDAO.delete(resDiscountProduct);
	}
	
	public ResDiscountProduct saveOrUpdate(ResDiscountProduct resDiscountProduct)
	{
		return resDiscountProductDAO.saveOrUpdate( resDiscountProduct);
	}

	public ResDiscountProduct load(Long id )
	{
		return resDiscountProductDAO.load( id );
	}

	
	public List<ResDiscountProduct> loadAll()
	{
		return resDiscountProductDAO.loadAll();
	}


	public List<ResDiscountProduct> loadByNamedQuery(String queryName)
	{
		return resDiscountProductDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResDiscountProduct> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resDiscountProductDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResDiscountProduct> search( Map<String, Object> criteria )
	{
		return resDiscountProductDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resDiscountProductDAO.countAll();
	}

	public List<ResDiscountProduct> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resDiscountProductDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResDiscountProduct> loadAll(Integer startPage , Integer pageSize )
	{

		return resDiscountProductDAO.loadAll( startPage ,  pageSize );
	}

}
