/*
 * Created on 24 Mar 2016 ( Time 12:52:05 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResDashboardSettingsService;
import com.itigeeks.restaurant.common.entity.schema.ResDashboardSettings;
import com.itigeeks.restaurant.dataaccess.dao.ResDashboardSettingsDAO;
/**
 * Implementation of ResDashboardSettingsService
 */
@Service
public class ResDashboardSettingsServiceImpl implements ResDashboardSettingsService {


	@Autowired
	private ResDashboardSettingsDAO resDashboardSettingsDAO;

	public void delete(ResDashboardSettings resDashboardSettings)
	{
		 resDashboardSettingsDAO.delete(resDashboardSettings);
	}
	
	public ResDashboardSettings saveOrUpdate(ResDashboardSettings resDashboardSettings)
	{
		return resDashboardSettingsDAO.saveOrUpdate( resDashboardSettings);
	}

	public ResDashboardSettings load(Long id )
	{
		return resDashboardSettingsDAO.load( id );
	}

	
	public List<ResDashboardSettings> loadAll()
	{
		return resDashboardSettingsDAO.loadAll();
	}


	public List<ResDashboardSettings> loadByNamedQuery(String queryName)
	{
		return resDashboardSettingsDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResDashboardSettings> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resDashboardSettingsDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResDashboardSettings> search( Map<String, Object> criteria )
	{
		return resDashboardSettingsDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resDashboardSettingsDAO.countAll();
	}

	public List<ResDashboardSettings> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resDashboardSettingsDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResDashboardSettings> loadAll(Integer startPage , Integer pageSize )
	{

		return resDashboardSettingsDAO.loadAll( startPage ,  pageSize );
	}

}
