/*
 * Created on 20 Mar 2016 ( Time 14:19:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResDiscountService;
import com.itigeeks.restaurant.common.entity.schema.ResDiscount;
import com.itigeeks.restaurant.dataaccess.dao.ResDiscountDAO;
/**
 * Implementation of ResDiscountService
 */
@Service
public class ResDiscountServiceImpl implements ResDiscountService {


	@Autowired
	private ResDiscountDAO resDiscountDAO;

	public void delete(ResDiscount resDiscount)
	{
		 resDiscountDAO.delete(resDiscount);
	}
	
	public ResDiscount saveOrUpdate(ResDiscount resDiscount)
	{
		return resDiscountDAO.saveOrUpdate( resDiscount);
	}

	public ResDiscount load(Long id )
	{
		return resDiscountDAO.load( id );
	}

	
	public List<ResDiscount> loadAll()
	{
		return resDiscountDAO.loadAll();
	}


	public List<ResDiscount> loadByNamedQuery(String queryName)
	{
		return resDiscountDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResDiscount> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resDiscountDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResDiscount> search( Map<String, Object> criteria )
	{
		return resDiscountDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resDiscountDAO.countAll();
	}

}
