/*
 * Created on 20 Mar 2016 ( Time 14:19:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResFlaggedOccassionService;
import com.itigeeks.restaurant.common.entity.schema.ResFlaggedOccassion;
import com.itigeeks.restaurant.dataaccess.dao.ResFlaggedOccassionDAO;
/**
 * Implementation of ResFlaggedOccassionService
 */
@Service
public class ResFlaggedOccassionServiceImpl implements ResFlaggedOccassionService {


	@Autowired
	private ResFlaggedOccassionDAO resFlaggedOccassionDAO;

	public void delete(ResFlaggedOccassion resFlaggedOccassion)
	{
		 resFlaggedOccassionDAO.delete(resFlaggedOccassion);
	}
	
	public ResFlaggedOccassion saveOrUpdate(ResFlaggedOccassion resFlaggedOccassion)
	{
		return resFlaggedOccassionDAO.saveOrUpdate( resFlaggedOccassion);
	}

	public ResFlaggedOccassion load(Long id )
	{
		return resFlaggedOccassionDAO.load( id );
	}

	
	public List<ResFlaggedOccassion> loadAll()
	{
		return resFlaggedOccassionDAO.loadAll();
	}


	public List<ResFlaggedOccassion> loadByNamedQuery(String queryName)
	{
		return resFlaggedOccassionDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResFlaggedOccassion> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resFlaggedOccassionDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResFlaggedOccassion> search( Map<String, Object> criteria )
	{
		return resFlaggedOccassionDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resFlaggedOccassionDAO.countAll();
	}

}
