/*
 * Created on 24 Mar 2016 ( Time 12:52:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResInvoiceService;
import com.itigeeks.restaurant.common.entity.schema.ResInvoice;
import com.itigeeks.restaurant.dataaccess.dao.ResInvoiceDAO;
/**
 * Implementation of ResInvoiceService
 */
@Service
public class ResInvoiceServiceImpl implements ResInvoiceService {


	@Autowired
	private ResInvoiceDAO resInvoiceDAO;

	public void delete(ResInvoice resInvoice)
	{
		 resInvoiceDAO.delete(resInvoice);
	}
	
	public ResInvoice saveOrUpdate(ResInvoice resInvoice)
	{
		return resInvoiceDAO.saveOrUpdate( resInvoice);
	}

	public ResInvoice load(Long id )
	{
		return resInvoiceDAO.load( id );
	}

	
	public List<ResInvoice> loadAll()
	{
		return resInvoiceDAO.loadAll();
	}


	public List<ResInvoice> loadByNamedQuery(String queryName)
	{
		return resInvoiceDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResInvoice> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resInvoiceDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResInvoice> search( Map<String, Object> criteria )
	{
		return resInvoiceDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resInvoiceDAO.countAll();
	}

	public List<ResInvoice> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resInvoiceDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResInvoice> loadAll(Integer startPage , Integer pageSize )
	{

		return resInvoiceDAO.loadAll( startPage ,  pageSize );
	}

}
