/*
 * Created on 24 Mar 2016 ( Time 12:52:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResModemService;
import com.itigeeks.restaurant.common.entity.schema.ResModem;
import com.itigeeks.restaurant.dataaccess.dao.ResModemDAO;
/**
 * Implementation of ResModemService
 */
@Service
public class ResModemServiceImpl implements ResModemService {


	@Autowired
	private ResModemDAO resModemDAO;

	public void delete(ResModem resModem)
	{
		 resModemDAO.delete(resModem);
	}
	
	public ResModem saveOrUpdate(ResModem resModem)
	{
		return resModemDAO.saveOrUpdate( resModem);
	}

	public ResModem load(Long id )
	{
		return resModemDAO.load( id );
	}

	
	public List<ResModem> loadAll()
	{
		return resModemDAO.loadAll();
	}


	public List<ResModem> loadByNamedQuery(String queryName)
	{
		return resModemDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResModem> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resModemDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResModem> search( Map<String, Object> criteria )
	{
		return resModemDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resModemDAO.countAll();
	}

	public List<ResModem> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resModemDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResModem> loadAll(Integer startPage , Integer pageSize )
	{

		return resModemDAO.loadAll( startPage ,  pageSize );
	}

}
