/*
 * Created on 24 Mar 2016 ( Time 12:52:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResNumberIdentifierService;
import com.itigeeks.restaurant.common.entity.schema.ResNumberIdentifier;
import com.itigeeks.restaurant.dataaccess.dao.ResNumberIdentifierDAO;
/**
 * Implementation of ResNumberIdentifierService
 */
@Service
public class ResNumberIdentifierServiceImpl implements ResNumberIdentifierService {


	@Autowired
	private ResNumberIdentifierDAO resNumberIdentifierDAO;

	public void delete(ResNumberIdentifier resNumberIdentifier)
	{
		 resNumberIdentifierDAO.delete(resNumberIdentifier);
	}
	
	public ResNumberIdentifier saveOrUpdate(ResNumberIdentifier resNumberIdentifier)
	{
		return resNumberIdentifierDAO.saveOrUpdate( resNumberIdentifier);
	}

	public ResNumberIdentifier load(Long id )
	{
		return resNumberIdentifierDAO.load( id );
	}

	
	public List<ResNumberIdentifier> loadAll()
	{
		return resNumberIdentifierDAO.loadAll();
	}


	public List<ResNumberIdentifier> loadByNamedQuery(String queryName)
	{
		return resNumberIdentifierDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResNumberIdentifier> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resNumberIdentifierDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResNumberIdentifier> search( Map<String, Object> criteria )
	{
		return resNumberIdentifierDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resNumberIdentifierDAO.countAll();
	}

	public List<ResNumberIdentifier> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resNumberIdentifierDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResNumberIdentifier> loadAll(Integer startPage , Integer pageSize )
	{

		return resNumberIdentifierDAO.loadAll( startPage ,  pageSize );
	}

}
