/*
 * Created on 20 Mar 2016 ( Time 14:19:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResOrderTypeService;
import com.itigeeks.restaurant.common.entity.schema.ResOrderType;
import com.itigeeks.restaurant.dataaccess.dao.ResOrderTypeDAO;
/**
 * Implementation of ResOrderTypeService
 */
@Service
public class ResOrderTypeServiceImpl implements ResOrderTypeService {


	@Autowired
	private ResOrderTypeDAO resOrderTypeDAO;

	public void delete(ResOrderType resOrderType)
	{
		 resOrderTypeDAO.delete(resOrderType);
	}
	
	public ResOrderType saveOrUpdate(ResOrderType resOrderType)
	{
		return resOrderTypeDAO.saveOrUpdate( resOrderType);
	}

	public ResOrderType load(Long id )
	{
		return resOrderTypeDAO.load( id );
	}

	
	public List<ResOrderType> loadAll()
	{
		return resOrderTypeDAO.loadAll();
	}


	public List<ResOrderType> loadByNamedQuery(String queryName)
	{
		return resOrderTypeDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResOrderType> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resOrderTypeDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResOrderType> search( Map<String, Object> criteria )
	{
		return resOrderTypeDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resOrderTypeDAO.countAll();
	}

}
