/*
 * Created on 20 Mar 2016 ( Time 14:19:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResOrderCategoryService;
import com.itigeeks.restaurant.common.entity.schema.ResOrderCategory;
import com.itigeeks.restaurant.dataaccess.dao.ResOrderCategoryDAO;
/**
 * Implementation of ResOrderCategoryService
 */
@Service
public class ResOrderCategoryServiceImpl implements ResOrderCategoryService {


	@Autowired
	private ResOrderCategoryDAO resOrderCategoryDAO;

	public void delete(ResOrderCategory resOrderCategory)
	{
		 resOrderCategoryDAO.delete(resOrderCategory);
	}
	
	public ResOrderCategory saveOrUpdate(ResOrderCategory resOrderCategory)
	{
		return resOrderCategoryDAO.saveOrUpdate( resOrderCategory);
	}

	public ResOrderCategory load(Long id )
	{
		return resOrderCategoryDAO.load( id );
	}

	
	public List<ResOrderCategory> loadAll()
	{
		return resOrderCategoryDAO.loadAll();
	}


	public List<ResOrderCategory> loadByNamedQuery(String queryName)
	{
		return resOrderCategoryDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResOrderCategory> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resOrderCategoryDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResOrderCategory> search( Map<String, Object> criteria )
	{
		return resOrderCategoryDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resOrderCategoryDAO.countAll();
	}

}
