/*
 * Created on 20 Mar 2016 ( Time 14:19:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResOrderReplicaService;
import com.itigeeks.restaurant.common.entity.schema.ResOrderReplica;
import com.itigeeks.restaurant.dataaccess.dao.ResOrderReplicaDAO;
/**
 * Implementation of ResOrderReplicaService
 */
@Service
public class ResOrderReplicaServiceImpl implements ResOrderReplicaService {


	@Autowired
	private ResOrderReplicaDAO resOrderReplicaDAO;

	public void delete(ResOrderReplica resOrderReplica)
	{
		 resOrderReplicaDAO.delete(resOrderReplica);
	}
	
	public ResOrderReplica saveOrUpdate(ResOrderReplica resOrderReplica)
	{
		return resOrderReplicaDAO.saveOrUpdate( resOrderReplica);
	}

	public ResOrderReplica load(Long id )
	{
		return resOrderReplicaDAO.load( id );
	}

	
	public List<ResOrderReplica> loadAll()
	{
		return resOrderReplicaDAO.loadAll();
	}


	public List<ResOrderReplica> loadByNamedQuery(String queryName)
	{
		return resOrderReplicaDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResOrderReplica> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resOrderReplicaDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResOrderReplica> search( Map<String, Object> criteria )
	{
		return resOrderReplicaDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resOrderReplicaDAO.countAll();
	}

}
