/*
 * Created on 20 Mar 2016 ( Time 14:19:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResOrderProductAddonService;
import com.itigeeks.restaurant.common.entity.schema.ResOrderProductAddon;
import com.itigeeks.restaurant.dataaccess.dao.ResOrderProductAddonDAO;
/**
 * Implementation of ResOrderProductAddonService
 */
@Service
public class ResOrderProductAddonServiceImpl implements ResOrderProductAddonService {


	@Autowired
	private ResOrderProductAddonDAO resOrderProductAddonDAO;

	public void delete(ResOrderProductAddon resOrderProductAddon)
	{
		 resOrderProductAddonDAO.delete(resOrderProductAddon);
	}
	
	public ResOrderProductAddon saveOrUpdate(ResOrderProductAddon resOrderProductAddon)
	{
		return resOrderProductAddonDAO.saveOrUpdate( resOrderProductAddon);
	}

	public ResOrderProductAddon load(Long id )
	{
		return resOrderProductAddonDAO.load( id );
	}

	
	public List<ResOrderProductAddon> loadAll()
	{
		return resOrderProductAddonDAO.loadAll();
	}


	public List<ResOrderProductAddon> loadByNamedQuery(String queryName)
	{
		return resOrderProductAddonDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResOrderProductAddon> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resOrderProductAddonDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResOrderProductAddon> search( Map<String, Object> criteria )
	{
		return resOrderProductAddonDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resOrderProductAddonDAO.countAll();
	}

}
