/*
 * Created on 20 Mar 2016 ( Time 14:19:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResOrderDeleteLogService;
import com.itigeeks.restaurant.common.entity.schema.ResOrderDeleteLog;
import com.itigeeks.restaurant.dataaccess.dao.ResOrderDeleteLogDAO;
/**
 * Implementation of ResOrderDeleteLogService
 */
@Service
public class ResOrderDeleteLogServiceImpl implements ResOrderDeleteLogService {


	@Autowired
	private ResOrderDeleteLogDAO resOrderDeleteLogDAO;

	public void delete(ResOrderDeleteLog resOrderDeleteLog)
	{
		 resOrderDeleteLogDAO.delete(resOrderDeleteLog);
	}
	
	public ResOrderDeleteLog saveOrUpdate(ResOrderDeleteLog resOrderDeleteLog)
	{
		return resOrderDeleteLogDAO.saveOrUpdate( resOrderDeleteLog);
	}

	public ResOrderDeleteLog load(Long id )
	{
		return resOrderDeleteLogDAO.load( id );
	}

	
	public List<ResOrderDeleteLog> loadAll()
	{
		return resOrderDeleteLogDAO.loadAll();
	}


	public List<ResOrderDeleteLog> loadByNamedQuery(String queryName)
	{
		return resOrderDeleteLogDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResOrderDeleteLog> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resOrderDeleteLogDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResOrderDeleteLog> search( Map<String, Object> criteria )
	{
		return resOrderDeleteLogDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resOrderDeleteLogDAO.countAll();
	}

}
