/*
 * Created on 24 Mar 2016 ( Time 12:52:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResOrderActionTypeService;
import com.itigeeks.restaurant.common.entity.schema.ResOrderActionType;
import com.itigeeks.restaurant.dataaccess.dao.ResOrderActionTypeDAO;
/**
 * Implementation of ResOrderActionTypeService
 */
@Service
public class ResOrderActionTypeServiceImpl implements ResOrderActionTypeService {


	@Autowired
	private ResOrderActionTypeDAO resOrderActionTypeDAO;

	public void delete(ResOrderActionType resOrderActionType)
	{
		 resOrderActionTypeDAO.delete(resOrderActionType);
	}
	
	public ResOrderActionType saveOrUpdate(ResOrderActionType resOrderActionType)
	{
		return resOrderActionTypeDAO.saveOrUpdate( resOrderActionType);
	}

	public ResOrderActionType load(Long id )
	{
		return resOrderActionTypeDAO.load( id );
	}

	
	public List<ResOrderActionType> loadAll()
	{
		return resOrderActionTypeDAO.loadAll();
	}


	public List<ResOrderActionType> loadByNamedQuery(String queryName)
	{
		return resOrderActionTypeDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResOrderActionType> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resOrderActionTypeDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResOrderActionType> search( Map<String, Object> criteria )
	{
		return resOrderActionTypeDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resOrderActionTypeDAO.countAll();
	}

	public List<ResOrderActionType> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resOrderActionTypeDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResOrderActionType> loadAll(Integer startPage , Integer pageSize )
	{

		return resOrderActionTypeDAO.loadAll( startPage ,  pageSize );
	}

}
