/*
 * Created on 24 Mar 2016 ( Time 12:52:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResPromoService;
import com.itigeeks.restaurant.common.entity.schema.ResPromo;
import com.itigeeks.restaurant.dataaccess.dao.ResPromoDAO;
/**
 * Implementation of ResPromoService
 */
@Service
public class ResPromoServiceImpl implements ResPromoService {


	@Autowired
	private ResPromoDAO resPromoDAO;

	public void delete(ResPromo resPromo)
	{
		 resPromoDAO.delete(resPromo);
	}
	
	public ResPromo saveOrUpdate(ResPromo resPromo)
	{
		return resPromoDAO.saveOrUpdate( resPromo);
	}

	public ResPromo load(Long id )
	{
		return resPromoDAO.load( id );
	}

	
	public List<ResPromo> loadAll()
	{
		return resPromoDAO.loadAll();
	}


	public List<ResPromo> loadByNamedQuery(String queryName)
	{
		return resPromoDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResPromo> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resPromoDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResPromo> search( Map<String, Object> criteria )
	{
		return resPromoDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resPromoDAO.countAll();
	}

	public List<ResPromo> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resPromoDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResPromo> loadAll(Integer startPage , Integer pageSize )
	{

		return resPromoDAO.loadAll( startPage ,  pageSize );
	}

}
