/*
 * Created on 24 Mar 2016 ( Time 12:52:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResProductWithWithoutService;
import com.itigeeks.restaurant.common.entity.schema.ResProductWithWithout;
import com.itigeeks.restaurant.dataaccess.dao.ResProductWithWithoutDAO;
/**
 * Implementation of ResProductWithWithoutService
 */
@Service
public class ResProductWithWithoutServiceImpl implements ResProductWithWithoutService {


	@Autowired
	private ResProductWithWithoutDAO resProductWithWithoutDAO;

	public void delete(ResProductWithWithout resProductWithWithout)
	{
		 resProductWithWithoutDAO.delete(resProductWithWithout);
	}
	
	public ResProductWithWithout saveOrUpdate(ResProductWithWithout resProductWithWithout)
	{
		return resProductWithWithoutDAO.saveOrUpdate( resProductWithWithout);
	}

	public ResProductWithWithout load(Long id )
	{
		return resProductWithWithoutDAO.load( id );
	}

	
	public List<ResProductWithWithout> loadAll()
	{
		return resProductWithWithoutDAO.loadAll();
	}


	public List<ResProductWithWithout> loadByNamedQuery(String queryName)
	{
		return resProductWithWithoutDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResProductWithWithout> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resProductWithWithoutDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResProductWithWithout> search( Map<String, Object> criteria )
	{
		return resProductWithWithoutDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resProductWithWithoutDAO.countAll();
	}

	public List<ResProductWithWithout> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resProductWithWithoutDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResProductWithWithout> loadAll(Integer startPage , Integer pageSize )
	{

		return resProductWithWithoutDAO.loadAll( startPage ,  pageSize );
	}

}
