/*
 * Created on 20 Mar 2016 ( Time 14:19:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResPrintBlockCategoryService;
import com.itigeeks.restaurant.common.entity.schema.ResPrintBlockCategory;
import com.itigeeks.restaurant.dataaccess.dao.ResPrintBlockCategoryDAO;
/**
 * Implementation of ResPrintBlockCategoryService
 */
@Service
public class ResPrintBlockCategoryServiceImpl implements ResPrintBlockCategoryService {


	@Autowired
	private ResPrintBlockCategoryDAO resPrintBlockCategoryDAO;

	public void delete(ResPrintBlockCategory resPrintBlockCategory)
	{
		 resPrintBlockCategoryDAO.delete(resPrintBlockCategory);
	}
	
	public ResPrintBlockCategory saveOrUpdate(ResPrintBlockCategory resPrintBlockCategory)
	{
		return resPrintBlockCategoryDAO.saveOrUpdate( resPrintBlockCategory);
	}

	public ResPrintBlockCategory load(Long id )
	{
		return resPrintBlockCategoryDAO.load( id );
	}

	
	public List<ResPrintBlockCategory> loadAll()
	{
		return resPrintBlockCategoryDAO.loadAll();
	}


	public List<ResPrintBlockCategory> loadByNamedQuery(String queryName)
	{
		return resPrintBlockCategoryDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResPrintBlockCategory> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resPrintBlockCategoryDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResPrintBlockCategory> search( Map<String, Object> criteria )
	{
		return resPrintBlockCategoryDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resPrintBlockCategoryDAO.countAll();
	}

}
