/*
 * Created on 24 Mar 2016 ( Time 12:52:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResProductAddonService;
import com.itigeeks.restaurant.common.entity.schema.ResProductAddon;
import com.itigeeks.restaurant.dataaccess.dao.ResProductAddonDAO;
/**
 * Implementation of ResProductAddonService
 */
@Service
public class ResProductAddonServiceImpl implements ResProductAddonService {


	@Autowired
	private ResProductAddonDAO resProductAddonDAO;

	public void delete(ResProductAddon resProductAddon)
	{
		 resProductAddonDAO.delete(resProductAddon);
	}
	
	public ResProductAddon saveOrUpdate(ResProductAddon resProductAddon)
	{
		return resProductAddonDAO.saveOrUpdate( resProductAddon);
	}

	public ResProductAddon load(Long id )
	{
		return resProductAddonDAO.load( id );
	}

	
	public List<ResProductAddon> loadAll()
	{
		return resProductAddonDAO.loadAll();
	}


	public List<ResProductAddon> loadByNamedQuery(String queryName)
	{
		return resProductAddonDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResProductAddon> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resProductAddonDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResProductAddon> search( Map<String, Object> criteria )
	{
		return resProductAddonDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resProductAddonDAO.countAll();
	}

	public List<ResProductAddon> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resProductAddonDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResProductAddon> loadAll(Integer startPage , Integer pageSize )
	{

		return resProductAddonDAO.loadAll( startPage ,  pageSize );
	}

}
