/*
 * Created on 20 Mar 2016 ( Time 14:19:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResPrinterService;
import com.itigeeks.restaurant.common.entity.schema.ResPrinter;
import com.itigeeks.restaurant.dataaccess.dao.ResPrinterDAO;
/**
 * Implementation of ResPrinterService
 */
@Service
public class ResPrinterServiceImpl implements ResPrinterService {


	@Autowired
	private ResPrinterDAO resPrinterDAO;

	public void delete(ResPrinter resPrinter)
	{
		 resPrinterDAO.delete(resPrinter);
	}
	
	public ResPrinter saveOrUpdate(ResPrinter resPrinter)
	{
		return resPrinterDAO.saveOrUpdate( resPrinter);
	}

	public ResPrinter load(Long id )
	{
		return resPrinterDAO.load( id );
	}

	
	public List<ResPrinter> loadAll()
	{
		return resPrinterDAO.loadAll();
	}


	public List<ResPrinter> loadByNamedQuery(String queryName)
	{
		return resPrinterDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResPrinter> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resPrinterDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResPrinter> search( Map<String, Object> criteria )
	{
		return resPrinterDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resPrinterDAO.countAll();
	}

}
