/*
 * Created on 24 Mar 2016 ( Time 12:52:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResProductMiscService;
import com.itigeeks.restaurant.common.entity.schema.ResProductMisc;
import com.itigeeks.restaurant.dataaccess.dao.ResProductMiscDAO;
/**
 * Implementation of ResProductMiscService
 */
@Service
public class ResProductMiscServiceImpl implements ResProductMiscService {


	@Autowired
	private ResProductMiscDAO resProductMiscDAO;

	public void delete(ResProductMisc resProductMisc)
	{
		 resProductMiscDAO.delete(resProductMisc);
	}
	
	public ResProductMisc saveOrUpdate(ResProductMisc resProductMisc)
	{
		return resProductMiscDAO.saveOrUpdate( resProductMisc);
	}

	public ResProductMisc load(Long id )
	{
		return resProductMiscDAO.load( id );
	}

	
	public List<ResProductMisc> loadAll()
	{
		return resProductMiscDAO.loadAll();
	}


	public List<ResProductMisc> loadByNamedQuery(String queryName)
	{
		return resProductMiscDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResProductMisc> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resProductMiscDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResProductMisc> search( Map<String, Object> criteria )
	{
		return resProductMiscDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resProductMiscDAO.countAll();
	}

	public List<ResProductMisc> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resProductMiscDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResProductMisc> loadAll(Integer startPage , Integer pageSize )
	{

		return resProductMiscDAO.loadAll( startPage ,  pageSize );
	}

}
