/*
 * Created on 20 Mar 2016 ( Time 14:19:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResPrepLocationService;
import com.itigeeks.restaurant.common.entity.schema.ResPrepLocation;
import com.itigeeks.restaurant.dataaccess.dao.ResPrepLocationDAO;
/**
 * Implementation of ResPrepLocationService
 */
@Service
public class ResPrepLocationServiceImpl implements ResPrepLocationService {


	@Autowired
	private ResPrepLocationDAO resPrepLocationDAO;

	public void delete(ResPrepLocation resPrepLocation)
	{
		 resPrepLocationDAO.delete(resPrepLocation);
	}
	
	public ResPrepLocation saveOrUpdate(ResPrepLocation resPrepLocation)
	{
		return resPrepLocationDAO.saveOrUpdate( resPrepLocation);
	}

	public ResPrepLocation load(Long id )
	{
		return resPrepLocationDAO.load( id );
	}

	
	public List<ResPrepLocation> loadAll()
	{
		return resPrepLocationDAO.loadAll();
	}


	public List<ResPrepLocation> loadByNamedQuery(String queryName)
	{
		return resPrepLocationDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResPrepLocation> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resPrepLocationDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResPrepLocation> search( Map<String, Object> criteria )
	{
		return resPrepLocationDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resPrepLocationDAO.countAll();
	}

}
