/*
 * Created on 24 Mar 2016 ( Time 12:52:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResProductPurchaseHistoryService;
import com.itigeeks.restaurant.common.entity.schema.ResProductPurchaseHistory;
import com.itigeeks.restaurant.dataaccess.dao.ResProductPurchaseHistoryDAO;
/**
 * Implementation of ResProductPurchaseHistoryService
 */
@Service
public class ResProductPurchaseHistoryServiceImpl implements ResProductPurchaseHistoryService {


	@Autowired
	private ResProductPurchaseHistoryDAO resProductPurchaseHistoryDAO;

	public void delete(ResProductPurchaseHistory resProductPurchaseHistory)
	{
		 resProductPurchaseHistoryDAO.delete(resProductPurchaseHistory);
	}
	
	public ResProductPurchaseHistory saveOrUpdate(ResProductPurchaseHistory resProductPurchaseHistory)
	{
		return resProductPurchaseHistoryDAO.saveOrUpdate( resProductPurchaseHistory);
	}

	public ResProductPurchaseHistory load(Long id )
	{
		return resProductPurchaseHistoryDAO.load( id );
	}

	
	public List<ResProductPurchaseHistory> loadAll()
	{
		return resProductPurchaseHistoryDAO.loadAll();
	}


	public List<ResProductPurchaseHistory> loadByNamedQuery(String queryName)
	{
		return resProductPurchaseHistoryDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResProductPurchaseHistory> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resProductPurchaseHistoryDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResProductPurchaseHistory> search( Map<String, Object> criteria )
	{
		return resProductPurchaseHistoryDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resProductPurchaseHistoryDAO.countAll();
	}

	public List<ResProductPurchaseHistory> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resProductPurchaseHistoryDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResProductPurchaseHistory> loadAll(Integer startPage , Integer pageSize )
	{

		return resProductPurchaseHistoryDAO.loadAll( startPage ,  pageSize );
	}

}
