/*
 * Created on 24 Mar 2016 ( Time 12:52:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResPredefinedMessageService;
import com.itigeeks.restaurant.common.entity.schema.ResPredefinedMessage;
import com.itigeeks.restaurant.dataaccess.dao.ResPredefinedMessageDAO;
/**
 * Implementation of ResPredefinedMessageService
 */
@Service
public class ResPredefinedMessageServiceImpl implements ResPredefinedMessageService {


	@Autowired
	private ResPredefinedMessageDAO resPredefinedMessageDAO;

	public void delete(ResPredefinedMessage resPredefinedMessage)
	{
		 resPredefinedMessageDAO.delete(resPredefinedMessage);
	}
	
	public ResPredefinedMessage saveOrUpdate(ResPredefinedMessage resPredefinedMessage)
	{
		return resPredefinedMessageDAO.saveOrUpdate( resPredefinedMessage);
	}

	public ResPredefinedMessage load(Long id )
	{
		return resPredefinedMessageDAO.load( id );
	}

	
	public List<ResPredefinedMessage> loadAll()
	{
		return resPredefinedMessageDAO.loadAll();
	}


	public List<ResPredefinedMessage> loadByNamedQuery(String queryName)
	{
		return resPredefinedMessageDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResPredefinedMessage> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resPredefinedMessageDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResPredefinedMessage> search( Map<String, Object> criteria )
	{
		return resPredefinedMessageDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resPredefinedMessageDAO.countAll();
	}

	public List<ResPredefinedMessage> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resPredefinedMessageDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResPredefinedMessage> loadAll(Integer startPage , Integer pageSize )
	{

		return resPredefinedMessageDAO.loadAll( startPage ,  pageSize );
	}

}
