/*
 * Created on 20 Mar 2016 ( Time 14:19:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResProductService;
import com.itigeeks.restaurant.common.entity.schema.ResProduct;
import com.itigeeks.restaurant.dataaccess.dao.ResProductDAO;
/**
 * Implementation of ResProductService
 */
@Service
public class ResProductServiceImpl implements ResProductService {


	@Autowired
	private ResProductDAO resProductDAO;

	public void delete(ResProduct resProduct)
	{
		 resProductDAO.delete(resProduct);
	}
	
	public ResProduct saveOrUpdate(ResProduct resProduct)
	{
		return resProductDAO.saveOrUpdate( resProduct);
	}

	public ResProduct load(Long id )
	{
		return resProductDAO.load( id );
	}

	
	public List<ResProduct> loadAll()
	{
		return resProductDAO.loadAll();
	}


	public List<ResProduct> loadByNamedQuery(String queryName)
	{
		return resProductDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResProduct> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resProductDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResProduct> search( Map<String, Object> criteria )
	{
		return resProductDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resProductDAO.countAll();
	}

}
