/*
 * Created on 24 Mar 2016 ( Time 12:52:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResPrintBlockService;
import com.itigeeks.restaurant.common.entity.schema.ResPrintBlock;
import com.itigeeks.restaurant.dataaccess.dao.ResPrintBlockDAO;
/**
 * Implementation of ResPrintBlockService
 */
@Service
public class ResPrintBlockServiceImpl implements ResPrintBlockService {


	@Autowired
	private ResPrintBlockDAO resPrintBlockDAO;

	public void delete(ResPrintBlock resPrintBlock)
	{
		 resPrintBlockDAO.delete(resPrintBlock);
	}
	
	public ResPrintBlock saveOrUpdate(ResPrintBlock resPrintBlock)
	{
		return resPrintBlockDAO.saveOrUpdate( resPrintBlock);
	}

	public ResPrintBlock load(Long id )
	{
		return resPrintBlockDAO.load( id );
	}

	
	public List<ResPrintBlock> loadAll()
	{
		return resPrintBlockDAO.loadAll();
	}


	public List<ResPrintBlock> loadByNamedQuery(String queryName)
	{
		return resPrintBlockDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResPrintBlock> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resPrintBlockDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResPrintBlock> search( Map<String, Object> criteria )
	{
		return resPrintBlockDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resPrintBlockDAO.countAll();
	}

	public List<ResPrintBlock> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resPrintBlockDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResPrintBlock> loadAll(Integer startPage , Integer pageSize )
	{

		return resPrintBlockDAO.loadAll( startPage ,  pageSize );
	}

}
