/*
 * Created on 20 Mar 2016 ( Time 14:19:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResQuantityTypeConversionService;
import com.itigeeks.restaurant.common.entity.schema.ResQuantityTypeConversion;
import com.itigeeks.restaurant.dataaccess.dao.ResQuantityTypeConversionDAO;
/**
 * Implementation of ResQuantityTypeConversionService
 */
@Service
public class ResQuantityTypeConversionServiceImpl implements ResQuantityTypeConversionService {


	@Autowired
	private ResQuantityTypeConversionDAO resQuantityTypeConversionDAO;

	public void delete(ResQuantityTypeConversion resQuantityTypeConversion)
	{
		 resQuantityTypeConversionDAO.delete(resQuantityTypeConversion);
	}
	
	public ResQuantityTypeConversion saveOrUpdate(ResQuantityTypeConversion resQuantityTypeConversion)
	{
		return resQuantityTypeConversionDAO.saveOrUpdate( resQuantityTypeConversion);
	}

	public ResQuantityTypeConversion load(Long id )
	{
		return resQuantityTypeConversionDAO.load( id );
	}

	
	public List<ResQuantityTypeConversion> loadAll()
	{
		return resQuantityTypeConversionDAO.loadAll();
	}


	public List<ResQuantityTypeConversion> loadByNamedQuery(String queryName)
	{
		return resQuantityTypeConversionDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResQuantityTypeConversion> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resQuantityTypeConversionDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResQuantityTypeConversion> search( Map<String, Object> criteria )
	{
		return resQuantityTypeConversionDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resQuantityTypeConversionDAO.countAll();
	}

}
