/*
 * Created on 24 Mar 2016 ( Time 12:52:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResQuantityTypeService;
import com.itigeeks.restaurant.common.entity.schema.ResQuantityType;
import com.itigeeks.restaurant.dataaccess.dao.ResQuantityTypeDAO;
/**
 * Implementation of ResQuantityTypeService
 */
@Service
public class ResQuantityTypeServiceImpl implements ResQuantityTypeService {


	@Autowired
	private ResQuantityTypeDAO resQuantityTypeDAO;

	public void delete(ResQuantityType resQuantityType)
	{
		 resQuantityTypeDAO.delete(resQuantityType);
	}
	
	public ResQuantityType saveOrUpdate(ResQuantityType resQuantityType)
	{
		return resQuantityTypeDAO.saveOrUpdate( resQuantityType);
	}

	public ResQuantityType load(Long id )
	{
		return resQuantityTypeDAO.load( id );
	}

	
	public List<ResQuantityType> loadAll()
	{
		return resQuantityTypeDAO.loadAll();
	}


	public List<ResQuantityType> loadByNamedQuery(String queryName)
	{
		return resQuantityTypeDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResQuantityType> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resQuantityTypeDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResQuantityType> search( Map<String, Object> criteria )
	{
		return resQuantityTypeDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resQuantityTypeDAO.countAll();
	}

	public List<ResQuantityType> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resQuantityTypeDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResQuantityType> loadAll(Integer startPage , Integer pageSize )
	{

		return resQuantityTypeDAO.loadAll( startPage ,  pageSize );
	}

}
