/*
 * Created on 20 Mar 2016 ( Time 14:19:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResReservationInvoiceService;
import com.itigeeks.restaurant.common.entity.schema.ResReservationInvoice;
import com.itigeeks.restaurant.dataaccess.dao.ResReservationInvoiceDAO;
/**
 * Implementation of ResReservationInvoiceService
 */
@Service
public class ResReservationInvoiceServiceImpl implements ResReservationInvoiceService {


	@Autowired
	private ResReservationInvoiceDAO resReservationInvoiceDAO;

	public void delete(ResReservationInvoice resReservationInvoice)
	{
		 resReservationInvoiceDAO.delete(resReservationInvoice);
	}
	
	public ResReservationInvoice saveOrUpdate(ResReservationInvoice resReservationInvoice)
	{
		return resReservationInvoiceDAO.saveOrUpdate( resReservationInvoice);
	}

	public ResReservationInvoice load(Long id )
	{
		return resReservationInvoiceDAO.load( id );
	}

	
	public List<ResReservationInvoice> loadAll()
	{
		return resReservationInvoiceDAO.loadAll();
	}


	public List<ResReservationInvoice> loadByNamedQuery(String queryName)
	{
		return resReservationInvoiceDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResReservationInvoice> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resReservationInvoiceDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResReservationInvoice> search( Map<String, Object> criteria )
	{
		return resReservationInvoiceDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resReservationInvoiceDAO.countAll();
	}

}
