/*
 * Created on 20 Mar 2016 ( Time 14:19:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResReportsService;
import com.itigeeks.restaurant.common.entity.schema.ResReports;
import com.itigeeks.restaurant.dataaccess.dao.ResReportsDAO;
/**
 * Implementation of ResReportsService
 */
@Service
public class ResReportsServiceImpl implements ResReportsService {


	@Autowired
	private ResReportsDAO resReportsDAO;

	public void delete(ResReports resReports)
	{
		 resReportsDAO.delete(resReports);
	}
	
	public ResReports saveOrUpdate(ResReports resReports)
	{
		return resReportsDAO.saveOrUpdate( resReports);
	}

	public ResReports load(Long id )
	{
		return resReportsDAO.load( id );
	}

	
	public List<ResReports> loadAll()
	{
		return resReportsDAO.loadAll();
	}


	public List<ResReports> loadByNamedQuery(String queryName)
	{
		return resReportsDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResReports> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resReportsDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResReports> search( Map<String, Object> criteria )
	{
		return resReportsDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resReportsDAO.countAll();
	}

}
