/*
 * Created on 24 Mar 2016 ( Time 12:52:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResReservationTypeService;
import com.itigeeks.restaurant.common.entity.schema.ResReservationType;
import com.itigeeks.restaurant.dataaccess.dao.ResReservationTypeDAO;
/**
 * Implementation of ResReservationTypeService
 */
@Service
public class ResReservationTypeServiceImpl implements ResReservationTypeService {


	@Autowired
	private ResReservationTypeDAO resReservationTypeDAO;

	public void delete(ResReservationType resReservationType)
	{
		 resReservationTypeDAO.delete(resReservationType);
	}
	
	public ResReservationType saveOrUpdate(ResReservationType resReservationType)
	{
		return resReservationTypeDAO.saveOrUpdate( resReservationType);
	}

	public ResReservationType load(Long id )
	{
		return resReservationTypeDAO.load( id );
	}

	
	public List<ResReservationType> loadAll()
	{
		return resReservationTypeDAO.loadAll();
	}


	public List<ResReservationType> loadByNamedQuery(String queryName)
	{
		return resReservationTypeDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResReservationType> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resReservationTypeDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResReservationType> search( Map<String, Object> criteria )
	{
		return resReservationTypeDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resReservationTypeDAO.countAll();
	}

	public List<ResReservationType> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resReservationTypeDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResReservationType> loadAll(Integer startPage , Integer pageSize )
	{

		return resReservationTypeDAO.loadAll( startPage ,  pageSize );
	}

}
