/*
 * Created on 20 Mar 2016 ( Time 14:19:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResReportSettingsService;
import com.itigeeks.restaurant.common.entity.schema.ResReportSettings;
import com.itigeeks.restaurant.dataaccess.dao.ResReportSettingsDAO;
/**
 * Implementation of ResReportSettingsService
 */
@Service
public class ResReportSettingsServiceImpl implements ResReportSettingsService {


	@Autowired
	private ResReportSettingsDAO resReportSettingsDAO;

	public void delete(ResReportSettings resReportSettings)
	{
		 resReportSettingsDAO.delete(resReportSettings);
	}
	
	public ResReportSettings saveOrUpdate(ResReportSettings resReportSettings)
	{
		return resReportSettingsDAO.saveOrUpdate( resReportSettings);
	}

	public ResReportSettings load(Long id )
	{
		return resReportSettingsDAO.load( id );
	}

	
	public List<ResReportSettings> loadAll()
	{
		return resReportSettingsDAO.loadAll();
	}


	public List<ResReportSettings> loadByNamedQuery(String queryName)
	{
		return resReportSettingsDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResReportSettings> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resReportSettingsDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResReportSettings> search( Map<String, Object> criteria )
	{
		return resReportSettingsDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resReportSettingsDAO.countAll();
	}

}
