/*
 * Created on 24 Mar 2016 ( Time 12:52:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResStatusService;
import com.itigeeks.restaurant.common.entity.schema.ResStatus;
import com.itigeeks.restaurant.dataaccess.dao.ResStatusDAO;
/**
 * Implementation of ResStatusService
 */
@Service
public class ResStatusServiceImpl implements ResStatusService {


	@Autowired
	private ResStatusDAO resStatusDAO;

	public void delete(ResStatus resStatus)
	{
		 resStatusDAO.delete(resStatus);
	}
	
	public ResStatus saveOrUpdate(ResStatus resStatus)
	{
		return resStatusDAO.saveOrUpdate( resStatus);
	}

	public ResStatus load(Long id )
	{
		return resStatusDAO.load( id );
	}

	
	public List<ResStatus> loadAll()
	{
		return resStatusDAO.loadAll();
	}


	public List<ResStatus> loadByNamedQuery(String queryName)
	{
		return resStatusDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResStatus> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resStatusDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResStatus> search( Map<String, Object> criteria )
	{
		return resStatusDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resStatusDAO.countAll();
	}

	public List<ResStatus> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resStatusDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResStatus> loadAll(Integer startPage , Integer pageSize )
	{

		return resStatusDAO.loadAll( startPage ,  pageSize );
	}

}
