/*
 * Created on 20 Mar 2016 ( Time 14:19:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResStateService;
import com.itigeeks.restaurant.common.entity.schema.ResState;
import com.itigeeks.restaurant.dataaccess.dao.ResStateDAO;
/**
 * Implementation of ResStateService
 */
@Service
public class ResStateServiceImpl implements ResStateService {


	@Autowired
	private ResStateDAO resStateDAO;

	public void delete(ResState resState)
	{
		 resStateDAO.delete(resState);
	}
	
	public ResState saveOrUpdate(ResState resState)
	{
		return resStateDAO.saveOrUpdate( resState);
	}

	public ResState load(Long id )
	{
		return resStateDAO.load( id );
	}

	
	public List<ResState> loadAll()
	{
		return resStateDAO.loadAll();
	}


	public List<ResState> loadByNamedQuery(String queryName)
	{
		return resStateDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResState> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resStateDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResState> search( Map<String, Object> criteria )
	{
		return resStateDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resStateDAO.countAll();
	}

}
