/*
 * Created on 24 Mar 2016 ( Time 12:52:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResTerminalService;
import com.itigeeks.restaurant.common.entity.schema.ResTerminal;
import com.itigeeks.restaurant.dataaccess.dao.ResTerminalDAO;
/**
 * Implementation of ResTerminalService
 */
@Service
public class ResTerminalServiceImpl implements ResTerminalService {


	@Autowired
	private ResTerminalDAO resTerminalDAO;

	public void delete(ResTerminal resTerminal)
	{
		 resTerminalDAO.delete(resTerminal);
	}
	
	public ResTerminal saveOrUpdate(ResTerminal resTerminal)
	{
		return resTerminalDAO.saveOrUpdate( resTerminal);
	}

	public ResTerminal load(Long id )
	{
		return resTerminalDAO.load( id );
	}

	
	public List<ResTerminal> loadAll()
	{
		return resTerminalDAO.loadAll();
	}


	public List<ResTerminal> loadByNamedQuery(String queryName)
	{
		return resTerminalDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResTerminal> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resTerminalDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResTerminal> search( Map<String, Object> criteria )
	{
		return resTerminalDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resTerminalDAO.countAll();
	}

	public List<ResTerminal> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resTerminalDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResTerminal> loadAll(Integer startPage , Integer pageSize )
	{

		return resTerminalDAO.loadAll( startPage ,  pageSize );
	}

}
