/*
 * Created on 24 Mar 2016 ( Time 12:52:10 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.itigeeks.restaurant.business.serviceimpl;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.itigeeks.restaurant.business.service.ResVoucherExclusionsService;
import com.itigeeks.restaurant.common.entity.schema.ResVoucherExclusions;
import com.itigeeks.restaurant.dataaccess.dao.ResVoucherExclusionsDAO;
/**
 * Implementation of ResVoucherExclusionsService
 */
@Service
public class ResVoucherExclusionsServiceImpl implements ResVoucherExclusionsService {


	@Autowired
	private ResVoucherExclusionsDAO resVoucherExclusionsDAO;

	public void delete(ResVoucherExclusions resVoucherExclusions)
	{
		 resVoucherExclusionsDAO.delete(resVoucherExclusions);
	}
	
	public ResVoucherExclusions saveOrUpdate(ResVoucherExclusions resVoucherExclusions)
	{
		return resVoucherExclusionsDAO.saveOrUpdate( resVoucherExclusions);
	}

	public ResVoucherExclusions load(Long id )
	{
		return resVoucherExclusionsDAO.load( id );
	}

	
	public List<ResVoucherExclusions> loadAll()
	{
		return resVoucherExclusionsDAO.loadAll();
	}


	public List<ResVoucherExclusions> loadByNamedQuery(String queryName)
	{
		return resVoucherExclusionsDAO.loadByNamedQuery(queryName);
	}

	
	public List<ResVoucherExclusions> loadByNamedQuery(String queryName, Map<String, Object> queryParameters)
	{
		return resVoucherExclusionsDAO.loadByNamedQuery( queryName, queryParameters);
	}
	
	
	public List<ResVoucherExclusions> search( Map<String, Object> criteria )
	{
		return resVoucherExclusionsDAO.search(  criteria );
	}

	
	public Integer countAll()
	{
		return resVoucherExclusionsDAO.countAll();
	}

	public List<ResVoucherExclusions> search( Map<String, Object> criteria , Integer firstPage , Integer pageSize )
	{
		return resVoucherExclusionsDAO.search(  criteria  , firstPage , pageSize  );
	}

	public List<ResVoucherExclusions> loadAll(Integer startPage , Integer pageSize )
	{

		return resVoucherExclusionsDAO.loadAll( startPage ,  pageSize );
	}

}
