/*
 * Created on 24 Mar 2016 ( Time 16:42:54 ) Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite)

package com.itigeeks.restaurant.common.entity.schema;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.itigeeks.restaurant.common.entity.AbstractEntity;
// import javax.validation.constraints.* ;
// import org.hibernate.validator.constraints.* ;
import java.util.List;

/**
 * Persistent class for entity stored in table "res_flagged_occassion_type"
 * 
 * @author Telosys Tools Generator
 * 
 */

@Entity
@Table(name = "res_flagged_occassion_type", catalog = "viceroy")
// Define named queries here
@NamedQueries({@NamedQuery(name = "ResFlaggedOccassionType.countAll",
    query = "SELECT COUNT(x) FROM ResFlaggedOccassionType x")})
public class ResFlaggedOccassionType extends AbstractEntity implements Serializable {
  private static final long serialVersionUID = 1L;

  // ----------------------------------------------------------------------
  // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
  // ----------------------------------------------------------------------
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", nullable = false)
  private Long id;


  // ----------------------------------------------------------------------
  // ENTITY DATA FIELDS
  // ----------------------------------------------------------------------
  @Column(name = "flagged_occassion_type", length = 100)
  private String flaggedOccassionType;



  // ----------------------------------------------------------------------
  // ENTITY LINKS ( RELATIONSHIP )
  // ----------------------------------------------------------------------
  @OneToMany(mappedBy = "resFlaggedOccassionType", targetEntity = ResFlaggedOccassion.class)
  private List<ResFlaggedOccassion> listOfResFlaggedOccassion;


  // ----------------------------------------------------------------------
  // CONSTRUCTOR(S)
  // ----------------------------------------------------------------------
  public ResFlaggedOccassionType() {
    super();
  }

  // ----------------------------------------------------------------------
  // GETTER & SETTER FOR THE KEY FIELD
  // ----------------------------------------------------------------------
  public void setId(Long id) {
    this.id = id;
  }

  public Long getId() {
    return this.id;
  }

  // ----------------------------------------------------------------------
  // GETTERS & SETTERS FOR FIELDS
  // ----------------------------------------------------------------------
  // --- DATABASE MAPPING : flagged_occassion_type ( VARCHAR )
  public void setFlaggedOccassionType(String flaggedOccassionType) {
    this.flaggedOccassionType = flaggedOccassionType;
  }

  public String getFlaggedOccassionType() {
    return this.flaggedOccassionType;
  }


  // ----------------------------------------------------------------------
  // GETTERS & SETTERS FOR LINKS
  // ----------------------------------------------------------------------
  public void setListOfResFlaggedOccassion(List<ResFlaggedOccassion> listOfResFlaggedOccassion) {
    this.listOfResFlaggedOccassion = listOfResFlaggedOccassion;
  }

  public List<ResFlaggedOccassion> getListOfResFlaggedOccassion() {
    return this.listOfResFlaggedOccassion;
  }


  // ----------------------------------------------------------------------
  // toString METHOD
  // ----------------------------------------------------------------------
  public String toString() {
    StringBuffer sb = new StringBuffer();
    sb.append("[");
    sb.append(id);
    sb.append("]:");
    sb.append(flaggedOccassionType);
    return sb.toString();
  }

}
