/*
 * Created on 24 Mar 2016 ( Time 16:42:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.itigeeks.restaurant.common.entity.schema;

import java.io.Serializable;
import com.itigeeks.restaurant.common.entity.AbstractEntity;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "res_order_product_addon"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="res_order_product_addon", catalog="viceroy" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ResOrderProductAddon.countAll", query="SELECT COUNT(x) FROM ResOrderProductAddon x" )
} )
public class ResOrderProductAddon extends AbstractEntity implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="quantity", nullable=false)
    private Short      quantity     ;

    @Column(name="price", nullable=false)
    private BigDecimal price        ;

	// "orderChildId" (column "order_child_id") is not defined by itself because used as FK in a link 
	// "productId" (column "product_id") is not defined by itself because used as FK in a link 
	// "addonId" (column "addon_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="order_child_id", referencedColumnName="id")
    private ResOrderChild resOrderChild;

    @ManyToOne
    @JoinColumn(name="addon_id", referencedColumnName="id")
    private ResAddon resAddon    ;

    @ManyToOne
    @JoinColumn(name="product_id", referencedColumnName="id")
    private ResProduct resProduct  ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ResOrderProductAddon()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id )
    {
        this.id = id ;
    }
    public Long getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : quantity ( SMALLINT ) 
    public void setQuantity( Short quantity )
    {
        this.quantity = quantity;
    }
    public Short getQuantity()
    {
        return this.quantity;
    }

    //--- DATABASE MAPPING : price ( DECIMAL ) 
    public void setPrice( BigDecimal price )
    {
        this.price = price;
    }
    public BigDecimal getPrice()
    {
        return this.price;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setResOrderChild( ResOrderChild resOrderChild )
    {
        this.resOrderChild = resOrderChild;
    }
    public ResOrderChild getResOrderChild()
    {
        return this.resOrderChild;
    }

    public void setResAddon( ResAddon resAddon )
    {
        this.resAddon = resAddon;
    }
    public ResAddon getResAddon()
    {
        return this.resAddon;
    }

    public void setResProduct( ResProduct resProduct )
    {
        this.resProduct = resProduct;
    }
    public ResProduct getResProduct()
    {
        return this.resProduct;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(quantity);
        sb.append("|");
        sb.append(price);
        return sb.toString(); 
    } 

}