/*
 * Created on 24 Mar 2016 ( Time 16:42:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.itigeeks.restaurant.common.entity.schema;

import java.io.Serializable;
import com.itigeeks.restaurant.common.entity.AbstractEntity;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "res_order_category"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="res_order_category", catalog="viceroy" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ResOrderCategory.countAll", query="SELECT COUNT(x) FROM ResOrderCategory x" )
} )
public class ResOrderCategory extends AbstractEntity implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long      id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="order_category", nullable=false, length=150)
    private String     orderCategory ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="resOrderCategory", targetEntity=ResCategoryOrderCategory.class)
    private List<ResCategoryOrderCategory> listOfResCategoryOrderCategory;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ResOrderCategory()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id )
    {
        this.id = id ;
    }
    public Long getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : order_category ( VARCHAR ) 
    public void setOrderCategory( String orderCategory )
    {
        this.orderCategory = orderCategory;
    }
    public String getOrderCategory()
    {
        return this.orderCategory;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfResCategoryOrderCategory( List<ResCategoryOrderCategory> listOfResCategoryOrderCategory )
    {
        this.listOfResCategoryOrderCategory = listOfResCategoryOrderCategory;
    }
    public List<ResCategoryOrderCategory> getListOfResCategoryOrderCategory()
    {
        return this.listOfResCategoryOrderCategory;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(orderCategory);
        return sb.toString(); 
    } 

}