/*
 * Created on 24 Mar 2016 ( Time 16:42:57 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.itigeeks.restaurant.common.entity.schema;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.itigeeks.restaurant.common.entity.AbstractEntity;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.util.List;

/**
 * Persistent class for entity stored in table "res_status"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="res_status", catalog="viceroy" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ResStatus.countAll", query="SELECT COUNT(x) FROM ResStatus x" )
} )
public class ResStatus extends AbstractEntity implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long      id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="status", nullable=false, length=150)
    private String     status       ;

    @Column(name="top_color", nullable=false, length=9)
    private String     topColor     ;

    @Column(name="bottom_color", nullable=false, length=9)
    private String     bottomColor  ;

    @Column(name="is_free", nullable=false)
    private Boolean    isFree       ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="resStatus", targetEntity=ResTable.class)
    private List<ResTable> listOfResTable;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ResStatus()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id )
    {
        this.id = id ;
    }
    public Long getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : status ( VARCHAR ) 
    public void setStatus( String status )
    {
        this.status = status;
    }
    public String getStatus()
    {
        return this.status;
    }

    //--- DATABASE MAPPING : top_color ( VARCHAR ) 
    public void setTopColor( String topColor )
    {
        this.topColor = topColor;
    }
    public String getTopColor()
    {
        return this.topColor;
    }

    //--- DATABASE MAPPING : bottom_color ( VARCHAR ) 
    public void setBottomColor( String bottomColor )
    {
        this.bottomColor = bottomColor;
    }
    public String getBottomColor()
    {
        return this.bottomColor;
    }

    //--- DATABASE MAPPING : is_free ( BIT ) 
    public void setIsFree( Boolean isFree )
    {
        this.isFree = isFree;
    }
    public Boolean getIsFree()
    {
        return this.isFree;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfResTable( List<ResTable> listOfResTable )
    {
        this.listOfResTable = listOfResTable;
    }
    public List<ResTable> getListOfResTable()
    {
        return this.listOfResTable;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(status);
        sb.append("|");
        sb.append(topColor);
        sb.append("|");
        sb.append(bottomColor);
        sb.append("|");
        sb.append(isFree);
        return sb.toString(); 
    } 

}