/*
 * Created on 24 Mar 2016 ( Time 16:42:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.itigeeks.restaurant.common.entity.schema;

import java.io.Serializable;

import com.itigeeks.restaurant.common.entity.AbstractEntity;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "res_settings"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="res_settings", catalog="viceroy" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ResSettings.countAll", query="SELECT COUNT(x) FROM ResSettings x" )
} )
public class ResSettings extends AbstractEntity implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long      id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="settings_name", nullable=false, length=150)
    private String     settingsName ;

    @Column(name="value", nullable=false, length=150)
    private String     value        ;

    @Column(name="is_flat", nullable=false)
    private Boolean    isFlat       ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ResSettings()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id )
    {
        this.id = id ;
    }
    public Long getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : settings_name ( VARCHAR ) 
    public void setSettingsName( String settingsName )
    {
        this.settingsName = settingsName;
    }
    public String getSettingsName()
    {
        return this.settingsName;
    }

    //--- DATABASE MAPPING : value ( VARCHAR ) 
    public void setValue( String value )
    {
        this.value = value;
    }
    public String getValue()
    {
        return this.value;
    }

    //--- DATABASE MAPPING : is_flat ( BIT ) 
    public void setIsFlat( Boolean isFlat )
    {
        this.isFlat = isFlat;
    }
    public Boolean getIsFlat()
    {
        return this.isFlat;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(settingsName);
        sb.append("|");
        sb.append(value);
        sb.append("|");
        sb.append(isFlat);
        return sb.toString(); 
    } 

}